markdown: kramdown
timezone: "Asia/Tokyo"
url: "https://p2pjapanese.github.io"
baseurl: ""

# --- Theme settings --- #

theme: jekyll-theme-slate
title: "P2P Electronic Japanese"
description: "Learn Japanese with Bitcoin"
show_downloads: false

# --- Other settings --- #

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md
